### ISSUE TITLE
Lmao?

### ISSUE THREAD

**Issue by 2ee4jnufew** [Studio-Plus/technology-pack-bugs-and-requests#1]
**Feature description**
Let's mod the portal. To have plates and stuff, cubes.

**Feature purpose**
It would be cool if there were plates both straight and at an angle.

**Comment by 2ee4jnufew** [comment]
play portal. You will understand what I mean.

**Comment by 2ee4jnufew** [comment]
look. In this game there are plates that move and thus the complex is built, it would be cool to make them even static. There are also cubes that you need to put on the buttons in order to go further.

**Comment by 404CoderNotFound** [comment]
I like the game portal, but there are already too many portal mods for ppg out there. You've got one by aspa, another one by brian (i think), and the list goes on.
