### ISSUE TITLE
Artificial Muscle Tendons

### ISSUE THREAD

**Issue by pilotmans** [Studio-Plus/technology-pack-bugs-and-requests#3]
**Feature description**

A strand of muscle that connects to an object that then connects to the back of the head and reads all of the humans' movements and relays them to the appropriate muscle strands, this in theory would allow power armor to exist.

**Feature purpose**
The purpose is to allow exoskeletons to exist that reliably read the humans' movements and relays them proper. Though these muscle strands would be placeable like a cable or wire would be. The muscle strands are intended to enhance the said users' movements and strength and allow them to wield incredibly heavy armor with minimal strain or problems.

**Additional context**
They are destructible but very durable, they should also generate a lot of heat so the armor in theory would need a "heatsink" for the muscle strands. Maybe add blue tooth heat conductors so you can realistically add muscle strands to arms without needing to worry about having problems connecting to the heat sink that may or may not be mounted on the back.

**Comment by Dawid23-Gamer** [comment]
I know that I am replying very shortly after this suggestion was made, but ArmorBehaviour in the StudioPlusAPI already solves the issue, the mass issue can be solved by making the armor lose all of its mass then regain it when detached.
